services:
  easynance-db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - ${POSTGRES_PORT}
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - easynance-db:/var/lib/postgresql/data
    command: -p ${POSTGRES_PORT}
  redis:
    container_name: easynance-redis
    image: 'redis:alpine'
    volumes:
      - easynance-redis:/data
    ports:
      - 6379:6379
volumes:
  easynance-redis:
  easynance-db:
    driver: local
