version: "2"

services:
  easynance-db:
    image: postgres:16.0-alpine3.18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - 5433
    ports:
      - '5433:5433'
    volumes:
      - easynance-db:/var/lib/postgresql/data
    command: -p 5433
volumes:
  easynance-db:
    driver: local
